# Generated by Django 5.1.1 on 2024-10-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_profile_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cookies_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
