# Generated by Django 5.1.1 on 2024-10-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_profile_cookies_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delete_frequency',
            field=models.CharField(choices=[('never', 'Никогда'), ('minute', 'Раз в минуту'), ('hour', 'Раз в час'), ('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], default='never', max_length=20),
        ),
    ]
