# Generated by Django 5.1.1 on 2024-10-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0005_profile_delete_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
