services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn toDo_app.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 30 --log-level debug
    volumes:
      - log_volume:/usr/src/app/log
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
        - ./.env.prod
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data
    env_file:
        - ./.env.db

  celery:
    build:
      context: ./
    command: celery -A toDo_app worker --loglevel=info
    depends_on:
      - web
      - redis

  celery-beat:
    build:
      context: ./
    command: celery -A toDo_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine
    ports:
        - "6379:6379"


  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume:
  log_volume:
