services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn toDo_app.wsgi:application --bind 0.0.0.0:8000 --workers 3 --max-requests 1000 --max-requests-jitter 100 --timeout 30 --log-level debug
    volumes:
      - log_volume:/usr/src/app/log
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - my_network
    restart: always

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    networks:
      - my_network
    restart: always

  celery:
    build:
      context: ./
    command: celery -A toDo_app worker --loglevel=info
    depends_on:
      - web
      - redis
    networks:
      - my_network
    restart: always

  celery-beat:
    build:
      context: ./
    command: celery -A toDo_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - web
      - redis
    networks:
      - my_network
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my_network
    restart: always


  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - my_network
    restart: always


volumes:
  postgres_data:
  static_volume:
  media_volume:
  log_volume:

networks:
  my_network:
    driver: bridge
